using EasiPosStockers.Branches;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace EasiPosStockers.CostCentres
{
    public class CostCentreManager : CostCentreManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CostCentreManager(ICostCentreRepository costCentreRepository)
            : base(costCentreRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}