using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace EasiPosStockers.Branches
{
    public class Branch : BranchBase
    {
        //<suite-custom-code-autogenerated>
        protected Branch()
        {

        }

        public Branch(Guid id, string branchReference, string branchName, string taxRegistrationNumber)
            : base(id, branchReference, branchName, taxRegistrationNumber)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}