using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace EasiPosStockers.Branches
{
    public class BranchManager : BranchManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BranchManager(IBranchRepository branchRepository)
            : base(branchRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}