using EasiPosStockers.Branches;
using EasiPosStockers.Products;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using EasiPosStockers.Permissions;
using EasiPosStockers.CostCentres;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using EasiPosStockers.Shared;

namespace EasiPosStockers.CostCentres
{
    public class CostCentresAppService : CostCentresAppServiceBase, ICostCentresAppService
    {
        //<suite-custom-code-autogenerated>
        public CostCentresAppService(ICostCentreRepository costCentreRepository, CostCentreManager costCentreManager, IDistributedCache<CostCentreExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Branch, Guid> branchRepository)
            : base(costCentreRepository, costCentreManager, excelDownloadTokenCache, branchRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}